name: 'shlokas'


services:
  database:
    build: ./database
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=dev
      - COUCHDB_PASSWORD=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  shlokas:
    name: shlokas
