name: Publish
on:
  release:
    types: [released]

env:
  REGISTRY:   ghcr.io
  DB_IMAGE_NAME: ghcr.io/${{ github.repository }}
  BS_IMAGE_NAME: ghcr.io/${{ github.repository }}-bootstrap
  IMAGE_TAG:  ${{ github.event.release.tag_name }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push "shlokas-db"
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DB_IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.DB_IMAGE_NAME }}:latest

      - name: Build and push "shlokas-db-bootstrap"
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.BS_IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.BS_IMAGE_NAME }}:latest
